name: 算法与程序设计 2022
title: "Demo"
description: TODO
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetheme: cayman