name: cpp-build
on: [push]
jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: cmake -S ${{ github.workspace }}/source -B build
      - name: build
        run: cmake --build build --target all