name: cpp-build
on: [push]


jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: cmake -S ${{ github.workspace }}/source -B build
      - name: build
        run: cmake --build build --target all

      - if: ${{ github.ref_type == "tag" }}
        name: Archive the release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: '${{ github.ref_name }}.zip'
          directory: "source"
  unix-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: cmake -S ${{ github.workspace }}/source -B build
      - name: build
        run: cmake --build build --target all
 
  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: CMake Configure
        run: cmake -S ${{ github.workspace }}/source -B ${{ github.workspace }}/build
      - name: CMake Build
        run: cmake --build ${{ github.workspace }}/build --target all